---

version: '3.8'
services:
  flask:
    env_file:
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}_${FLASK_CONTAINER_NAME}
    build:
      context: ./../../
      dockerfile: ./docker/local/python-flask/Dockerfile
      args:
        - FLASK_IMAGE=${FLASK_IMAGE}
        - FLASK_PORT=${FLASK_INTERNAL_PORT}
        - FLASK_SRC_DIR=${PROJ_DIR}
    ports:
      - ${FLASK_EXTERNAL_PORT}:${FLASK_INTERNAL_PORT}
    volumes:
      - ../../${PROJ_DIR}:/app/
    image: python-flask:latest
    restart: 'no'

...
