version: '3'
services:
  python-flask:
    env_file:
      - .env
    build:
      context: ./../../
      dockerfile: ./docker/local/python-flask/Dockerfile
      args:
        - PYTHON_IMAGE=${PYTHON_IMAGE}
    ports:
      - ${FLASK_EXTERNAL_PORT}:${FLASK_INTERNAL_PORT}
    volumes:
      - ../../src:/app/app
      - ../../config.py:/app/config.py
    image: ${PYTHON_IMAGE}
    restart: 'no'

