version: '3'
services:
  python-flask:
    env_file:
      - .env
    build:
      context: ./../../
      dockerfile: ./docker/local/python-flask/Dockerfile
      args:
        - FLASK_IMAGE=${FLASK_IMAGE}
    ports:
      - ${HOST_PORT}:${FLASK_PORT}
    volumes:
      - ../../src:/app/app
      - ../../config.py:/app/config.py
    image: python-flask:latest
    restart: 'no'

