---

version: '3.8'
services:
  flask:
    env_file:
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}_${PYTHON_CONTAINER_NAME}
    build:
      context: ./../../
      dockerfile: ${PYTHON_DOCKERFILE}
      args:
        - PYTHON_IMAGE=${PYTHON_BASE_IMAGE}
        - PYTHON_PORT=${PYTHON_INTERNAL_PORT}
        - SRC_DIR=${DOCKER_SRC_DIR}
    image: ${PYTHON_BASE_IMAGE}
    networks:
      - localnetwork
    ports:
      - ${PYTHON_EXTERNAL_PORT}:${PYTHON_INTERNAL_PORT}
    volumes:
      - ../../${DOCKER_SRC_DIR}:/app/
    labels:
      custom.project_name: ${COMPOSE_PROJECT_NAME}
      custom.components: flask
    restart: 'no'

networks:
  localnetwork:
    name: ${COMPOSE_PROJECT_NAME}_${DOCKER_NETWORK_NAME}
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: "${DOCKER_NETWORK_CIDR}"

...
