---

## This workflow is triggered in main and develop branches
## Client: Template
## Project: python-template
## Repository: https://github.com/novadevs-opensource/python-template.git
## Version: 0.0.1

name: Test - Build

on:
  push:
    branches:
      - main
      - develop

env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  DEPLOY_SERVER: github-runner
  DEPLOY_ENV: Testing
  DEPLOY_ACTION: Automatic

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Getting the branch name used in the deployment
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Downloading the repository
        uses: actions/checkout@v3

      - name: Getting Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Updating PIP
        run: pip install --upgrade pip

      - name: Installing project dependencies
        working-directory: src
        run: pip install -r requirements.txt

      - name: Running the application
        working-directory: src
        run: python __init__.py &

      - name: Checking if the application works
        run: |
          curl -s http://localhost:5000

      - name: Sending a notification if failure
        if: ${{ failure() }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"${{ env.SLACK_CHANNEL }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Server:* ${{ env.DEPLOY_SERVER }}\n\n *Workflow:* ${{ github.workflow }}\"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Repository:*\n${{ github.repository }}\"},{\"type\":\"mrkdwn\",\"text\":\"*Env:*\n${{ env.DEPLOY_ENV }}\"}]},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*User:*\n${{ github.triggering_actor }}\"},{\"type\":\"mrkdwn\",\"text\":\"*Action:*\n${{ env.DEPLOY_ACTION }}\"}]},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*BuildID:*\n${{ github.run_number }}\"},{\"type\":\"mrkdwn\",\"text\":\"*Status:*\n:x:\"}]},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Commit message:* ${{ github.event.head_commit.message }}\n\n *Commit URL:* ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}\"}}]}'

...
